
import java.awt.Font;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class PolaWyboru extends javax.swing.JFrame {

    /**
     * Creates new form PolaWyboru
     */
    public PolaWyboru() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pogrubionyCheckBox = new javax.swing.JCheckBox();
        pochylonyCheckBox = new javax.swing.JCheckBox();
        tEtykieta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pogrubionyCheckBox.setText("pogrubiony");
        pogrubionyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pogrubionyCheckBoxActionPerformed(evt);
            }
        });

        pochylonyCheckBox.setText("pochylony");
        pochylonyCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pochylonyCheckBoxActionPerformed(evt);
            }
        });

        tEtykieta.setText("Tekst do edycji");
        tEtykieta.setFont(new Font("Monospaced", Font.PLAIN, 15));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pogrubionyCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pochylonyCheckBox))
                    .addComponent(tEtykieta))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pogrubionyCheckBox)
                    .addComponent(pochylonyCheckBox))
                .addGap(38, 38, 38)
                .addComponent(tEtykieta)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pogrubionyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pogrubionyCheckBoxActionPerformed
        zmienStyle();
    }//GEN-LAST:event_pogrubionyCheckBoxActionPerformed

    private void pochylonyCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pochylonyCheckBoxActionPerformed
        zmienStyle();
    }//GEN-LAST:event_pochylonyCheckBoxActionPerformed

    private void zmienStyle()
    {
        int style = Font.PLAIN;
            if (pogrubionyCheckBox.isSelected()) style += Font.BOLD;
            if (pochylonyCheckBox.isSelected()) style += Font.ITALIC;
            tEtykieta.setFont(new Font(tEtykieta.getFont().getFamily(), style, tEtykieta.getFont().getSize()));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PolaWyboru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PolaWyboru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PolaWyboru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PolaWyboru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PolaWyboru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox pochylonyCheckBox;
    private javax.swing.JCheckBox pogrubionyCheckBox;
    private javax.swing.JLabel tEtykieta;
    // End of variables declaration//GEN-END:variables
}
